### ISSUE TITLE
https://zatech.github.io/site/ page doesn't display the signup button

### ISSUE THREAD

**Issue by oskarpearson** [zatech/site#1]
Hi

The zatech signup page doesn't correctly display the signup button at the moment. This is because now-examples-slackin-ovcpvznorx.now.sh never responds to network connections.

https://now-examples-slackin-ovcpvznorx.now.sh/slackin.js

Thanks!

Oskar

**Comment by n1c** [comment]
Hey I just checked and it's working for me; can you confirm it's still broken?

**Comment by oskarpearson** [comment]
It's back :) Thanks for your help!
