### ISSUE TITLE
Slack signup seems broken?

### ISSUE THREAD

**Issue by mzealey** [zatech/site#2]
Hi there, I've just tried to join slack via two different email addresses and got no message - is the signup code working correctly?

**Comment by n1c** [comment]
Yeah; seems like Slack may have removed the undocumented way we were doing invites. Will push a fix soon!

**Comment by n1c** [comment]
Fixed by https://github.com/zatech/site/commit/902fc49cd75a7a24b8cb2f86ad8fc6d1d24acb01. Thanks for the report!
